In [4]:
#NumPy Laboratory Practice Questions

#1. Array Creation & Properties

In [5]:
import numpy as np

In [6]:
#1.	Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.

In [7]:
list=[[10,20,30,40,50]]
arr=np.array(list)
print("Shape of Array",arr.shape)
print("Size of Array",arr.size)
print("Data type of Array",arr.dtype)

Shape of Array (1, 5)
Size of Array 5
Data type of Array int64


In [8]:
#2.	Create a 3 × 4 array containing numbers from 1 to 12.

In [9]:
list=np.arange(1,13).reshape(3,4)
print(list)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#3.	Create an array of zeros, an array of ones, and an identity matrix.

In [11]:
print("Array of zeroes",np.zeros(5))
print("Array of ones",np.ones(5))
print("Array of an identity matrix",np.eye(5))

Array of zeroes [0. 0. 0. 0. 0.]
Array of ones [1. 1. 1. 1. 1.]
Array of an identity matrix [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
#4.	Generate all even numbers between 10 and 50 using np.arange().

In [13]:
print("Even Numbers between 10 and 50 are",np.arange(10,50,2))

Even Numbers between 10 and 50 are [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [14]:
#5.	Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().

In [15]:
print("Array using linespace",np.linspace(0,1,10))

Array using linespace [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [16]:
#2. Array Arithmetic



In [17]:
#6.	Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and
#division

In [18]:
a1=[[10,20,30,40]]
arr1=np.array(a1)
a2=[[40,30,20,10]]
arr2=np.array(a2)
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr1/arr2)

[[50 50 50 50]]
[[ 30  10 -10 -30]]
[[400 600 600 400]]
[[0.25       0.66666667 1.5        4.        ]]


In [19]:
#7.	Calculate the square and cube of every element in a NumPy array.

In [20]:
print("square of every element of numpy array",arr1**2)
print("cube of every element of numpy array",arr2**3)

square of every element of numpy array [[ 100  400  900 1600]]
cube of every element of numpy array [[64000 27000  8000  1000]]


In [21]:
#8.	Increase every element of an array by 15%.

In [22]:
arr=np.array([10,20,30,40])
print(arr*1.15)

[11.5 23.  34.5 46. ]


In [23]:
#9.	Given two arrays, find their element-wise maximum and minimum.

In [24]:
print("max of two arrays",np.maximum(arr1,arr2))
print("max of two arrays",np.minimum(arr1,arr2))

max of two arrays [[40 30 30 40]]
max of two arrays [[10 20 20 10]]


In [25]:
#3. Indexing & Slicing

In [26]:
#10.	Create an array from 0 to 20 and extract the first five elements, last five elements, elements from index 5 to 15, and every second element.

In [27]:
a1=np.arange(0,20)
print(a1[0:6])
print(a1[-5:])
print(a1[5:15])

[0 1 2 3 4 5]
[15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14]


In [28]:
#11.	Replace the first five elements of an array with 100.

In [36]:
a1[0:6]=100
print(a1)

[100 100 100 100 100 100   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


In [30]:
#12.	Create an array and demonstrate the difference between a slice/view and a copy.

In [35]:
slice_view = a1[:3]
print(slice_view)
slice_copy = a1[:3].copy()
print(slice_copy)

[100 100 100]
[100 100 100]


In [31]:
#13.	Reverse a NumPy array using slicing.

In [34]:
reversed_arr = a1[::-1]
print("\nReversed Array:\n", reversed_arr)


Reversed Array:
 [ 19  18  17  16  15  14  13  12  11  10   9   8   7   6 100 100 100 100
 100 100]


In [ ]:
#4. 2-D Array Indexing & Slicing

In [ ]:
#14.	Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.

In [42]:
matrix_a = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

print("Second row:", matrix_a[1, :])      # Index 1 is the 2nd row
print("Third column:", matrix_a[:, 2])    # Index 2 is the 3rd column
print("Element 50:", matrix_a[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [ ]:
#15.	From the matrix above, extract the sub-matrix [[20,30],[50,60]].

In [43]:
sub_matrix = matrix_a[0:2, 1:3]
print("\nSub-matrix:\n", sub_matrix)


Sub-matrix:
 [[20 30]
 [50 60]]


In [ ]:
#16.	Create a 5 × 5 matrix containing 1–25 and extract the first row, last column, middle element, and top-left 3 × 3 matrix.

In [51]:
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
print("\nFirst row:", matrix_5x5[0, ])
print("Last column:", matrix_5x5[:, -1])
print("Middle element:", matrix_5x5[2, 2])
print("Top-left 3x3:\n", matrix_5x5[0:3, 0:3])


First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13
Top-left 3x3:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
#5. Reshaping & Transpose

In [ ]:
#17.	Create an array containing 1–12 and reshape it into a 3 × 4 matrix.

In [45]:
arr_1_12 = np.arange(1, 13)
matrix_3x4 = arr_1_12.reshape(3, 4)
print("3x4 Matrix:\n", matrix_3x4)


3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#18.	Reshape a 1-D array into a 2 × 5 matrix.

In [58]:
arr_10 = np.arange(10)
print(arr_10)
matrix_2x5 = arr_10.reshape(2, 5)
print("\n2x5 Matrix:\n", matrix_2x5)

[0 1 2 3 4 5 6 7 8 9]

2x5 Matrix:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [53]:
#19.	Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.

In [52]:
matrix_4x3 = matrix_3x4.T
print("\nTransposed to 4x3:\n", matrix_4x3)


Transposed to 4x3:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
#20.	Use transpose() and swapaxes() on a 3-D array.

In [57]:
array_3d = np.arange(24).reshape(2, 3, 4)
print("3D Array:\n", array_3d)
transposed_3d = array_3d.transpose()
swapped_3d = array_3d.swapaxes(0, 2)
print("\nTransposed 3D:\n", transposed_3d)
print("\nSwapped 3D:\n", swapped_3d)

3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Transposed 3D:
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]

Swapped 3D:
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [ ]:
#6. Matrix Operations

In [ ]:
#21.	Create two 3 × 3 matrices and perform element-wise addition and multiplication.

In [59]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [60]:
print("Element-wise Addition:\n", mat1 + mat2)
print("\nElement-wise Multiplication:\n", mat1 * mat2)

Element-wise Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
#22.	Calculate the matrix product of two compatible matrices using np.dot().

In [61]:
dot_product = np.dot(mat1, mat2)
print("\nMatrix Product:\n", dot_product)


Matrix Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#23.	Find the transpose of a matrix and calculate its dot product with the original matrix.

In [63]:
mat1_transposed = mat1.T
dot_with_transpose = np.dot(mat1, mat1_transposed)
print(mat1_transposed)
print("\nDot Product with Transpose:\n", dot_with_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]

Dot Product with Transpose:
 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [ ]:
#7. Universal Functions

In [ ]:
#24.	Calculate the square root of every element in an array using NumPy.

In [64]:
my_arr = np.array([1, 4, 9, 16])
print("Square roots:", np.sqrt(my_arr))

Square roots: [1. 2. 3. 4.]


In [ ]:
#25.	Calculate e^x for every element of an array.

In [65]:
print("Exponentials:", np.exp(my_arr))

Exponentials: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [ ]:
#26.	Generate a random array and calculate its square root, exponential, and absolute values.

In [66]:
rand_arr = np.random.rand(5) * 10
print("\nRandom Array:\n", rand_arr)
print("Square roots:", np.sqrt(rand_arr))
print("Absolute values:", np.abs(rand_arr))


Random Array:
 [3.64239739 4.63058687 9.66863453 0.05335315 1.24669877]
Square roots: [1.90850659 2.15187985 3.1094428  0.23098301 1.11655666]
Absolute values: [3.64239739 4.63058687 9.66863453 0.05335315 1.24669877]


In [ ]:
#27.	Generate two random arrays and find their element-wise maximum.

In [67]:
rand1 = np.random.rand(4)
rand2 = np.random.rand(4)
print("\nMax of two randoms:", np.maximum(rand1, rand2))


Max of two randoms: [0.7741333  0.75950901 0.88533705 0.7862128 ]


In [ ]:
#8. np.where()

In [ ]:
#28.	Given marks = np.array([35,72,48,90,55,28]), replace marks below 40 with 0 using np.where().

In [68]:
marks = np.array([35, 72, 48, 90, 55, 28])
# condition: marks < 40, if true: 0, if false: keep original mark
adjusted_marks = np.where(marks < 40, 0, marks)
print("Adjusted marks:", adjusted_marks)

Adjusted marks: [ 0 72 48 90 55  0]


In [ ]:
#29.	Given an income array, classify observations as 'High' if income ≥ 50,000 and 'Low' otherwise.

In [69]:
income = np.array([45000, 60000, 30000, 80000])
# condition: income >= 50000, if true: 'High', if false: 'Low'
classification = np.where(income >= 50000, 'High', 'Low')
print("\nIncome classification:", classification)


Income classification: ['Low' 'High' 'Low' 'High']


In [ ]:
#30.	Replace all values greater than 30 in an array with 100 using np.where().

In [70]:
values = np.array([10, 40, 25, 50])
adjusted_values = np.where(values > 30, 100, values)
print("\nValues adjusted:", adjusted_values)


Values adjusted: [ 10 100  25 100]


In [ ]:
#9. Statistical Operations

In [ ]:
#31.	Given a 3 × 3 matrix, calculate its total sum, mean, variance, and standard deviation.

In [71]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1. Basic Stats on the whole matrix
print("Total Sum:", np.sum(matrix))
print("Mean (Average):", np.mean(matrix))
print("Variance:", np.var(matrix))
print("Standard Deviation:", np.std(matrix))

Total Sum: 45
Mean (Average): 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611


In [ ]:
#32.	Calculate row-wise and column-wise sums using axis.

In [72]:
print("\nColumn-wise sum (Axis 0):", np.sum(matrix, axis=0))
print("Row-wise sum (Axis 1):", np.sum(matrix, axis=1))


Column-wise sum (Axis 0): [12 15 18]
Row-wise sum (Axis 1): [ 6 15 24]


In [ ]:
#33.	Given the marks of 10 students, calculate mean, standard deviation, minimum, and maximum.

In [73]:
student_marks = np.array([85, 92, 78, 90, 88, 76, 95, 89, 82, 91])
print("\nMarks Mean:", np.mean(student_marks))
print("Marks Min:", np.min(student_marks))
print("Marks Max:", np.max(student_marks))


Marks Mean: 86.6
Marks Min: 76
Marks Max: 95


In [ ]:
#34.	Demonstrate the difference between any() and all() using a Boolean array.

In [74]:
bool_arr = np.array([True, False, True])
print("\nany() - are ANY true?:", np.any(bool_arr))
print("all() - are ALL true?:", np.all(bool_arr))


any() - are ANY true?: True
all() - are ALL true?: False


In [ ]:
#10. Sorting & Unique Values

In [ ]:
#35.	Generate 10 random numbers and sort them.

In [75]:
random_nums = np.random.rand(10)
sorted_nums = np.sort(random_nums)
print("Sorted numbers:\n", sorted_nums)

Sorted numbers:
 [0.13784609 0.33767958 0.54369169 0.66612248 0.66967999 0.74150418
 0.81756999 0.97705685 0.98176543 0.99653811]


In [ ]:
#36.	Given an array containing repeated values, find its unique elements.

In [76]:
repeated_arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_vals = np.unique(repeated_arr)
print("\nUnique values:", unique_vals)


Unique values: [1 2 3 4 5]


In [ ]:
#37.	Given an array of student marks, find the unique marks.

In [77]:
marks_arr = np.array([85, 90, 85, 70, 90])
print("\nUnique marks:", np.unique(marks_arr))


Unique marks: [70 85 90]


In [ ]:
#38.	Use np.in1d() to check whether selected values occur in an array.

In [80]:
check_vals = np.in1d([2, 9], repeated_arr)
print("\nAre 2 and 9 present?:", check_vals)


Are 2 and 9 present?: [ True False]


/tmp/ipykernel_5404/759438316.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  check_vals = np.in1d([2, 9], repeated_arr)


In [ ]:
#11. Integrated Lab Questions

In [ ]:
#39.	Student Marks Analysis: Create a NumPy array containing marks of 10 students in 3 subjects.
#Calculate each student's total and average marks. Identify students whose average is ≥ 50 using np.where().

In [81]:
marks_matrix = np.random.randint(40, 100, size=(10, 3))
totals = np.sum(marks_matrix, axis=1)
averages = np.mean(marks_matrix, axis=1)
passed_students = np.where(averages >= 50)
print("Passed students (indices):", passed_students)

Passed students (indices): (array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)


In [ ]:
#40.	Matrix Analysis: Create a 4 × 4 matrix containing numbers 1–16. Find its transpose, row-wise sums, column-wise sums, mean, maximum, and minimum.
#Extract the central 2 × 2 matrix.

In [82]:
mat_4x4 = np.arange(1, 17).reshape(4, 4)
print("\n4x4 Transpose:\n", mat_4x4.T)
print("Central 2x2:\n", mat_4x4[1:3, 1:3])


4x4 Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Central 2x2:
 [[ 6  7]
 [10 11]]


In [ ]:
#41.	Random Data Analysis: Generate 20 observations using np.random.randn().
#Calculate the mean, standard deviation, minimum, maximum, and sorted values. Replace all negative observations with zero using np.where().

In [85]:
rand_20 = np.random.randn(20)
clean_data = np.where(rand_20 < 0, 0, rand_20)
print("Cleaned data:\n", clean_data)

Cleaned data:
 [0.72636347 0.26779659 1.06074129 0.         0.3298109  0.00252046
 0.56389016 0.22974006 0.         0.77315406 0.         0.69690176
 0.18860049 0.09786548 0.04520082 0.55861938 0.78772219 0.37322597
 0.         0.        ]


In [ ]:
#42.	Matrix Operations Challenge: Create two 3 × 3 matrices and perform element-wise addition, element-wise multiplication, matrix multiplication,
#transpose of the first matrix, and maximum/minimum of the resulting matrix.

In [87]:
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[2, 0, 1],
                     [3, 2, 0],
                     [1, 1, 3]])

addition_result = matrix_A + matrix_B
print("Element-wise Addition:\n", addition_result)

element_mult_result = matrix_A * matrix_B
print("\nElement-wise Multiplication:\n", element_mult_result)

matrix_mult_result = np.dot(matrix_A, matrix_B)
print("\nMatrix Multiplication (Dot Product):\n", matrix_mult_result)

transpose_A = matrix_A.T
print("\nTranspose of Matrix A:\n", transpose_A)

max_val = np.max(matrix_mult_result)
min_val = np.min(matrix_mult_result)

print("\nMaximum value in the multiplied matrix:", max_val)
print("Minimum value in the multiplied matrix:", min_val)

Element-wise Addition:
 [[ 3  2  4]
 [ 7  7  6]
 [ 8  9 12]]

Element-wise Multiplication:
 [[ 2  0  3]
 [12 10  0]
 [ 7  8 27]]

Matrix Multiplication (Dot Product):
 [[11  7 10]
 [29 16 22]
 [47 25 34]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Maximum value in the multiplied matrix: 47
Minimum value in the multiplied matrix: 7


In [ ]:
#43.	Array Manipulation Challenge: Create an array containing 1–24, reshape it into a 4 × 6 matrix, extract selected rows and columns, transpose it,
#calculate row/column statistics, and identify unique values.

In [89]:
arr_24 = np.arange(1, 25).reshape(4, 6)
subset = arr_24[1:3, 2:4]
print("\nSubset from 4x6:\n", subset)


Subset from 4x6:
 [[ 9 10]
 [15 16]]
